services:
  devcontainer:
    # Microsoft dev container image
    image: "mcr.microsoft.com/devcontainers/python:1-3.13-bookworm"

    # Forward the port for the FastAPI application
    ports:
      - "8000:8000"

    # Set default environment variables for OpenSearch (can be overridden)
    environment:
      - OPENSEARCH_HOST=localhost
      - OPENSEARCH_PORT=9200
      - OPENSEARCH_USE_SSL=false
      - OPENSEARCH_VERIFY_CERTS=false
    

  production:
    image: Dockerfile
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      - OPENSEARCH_HOST=localhost
      - OPENSEARCH_PORT=9200
      - OPENSEARCH_USE_SSL=false
      - OPENSEARCH_VERIFY_CERTS=false
    
    