"""
API routes for handling document uploads and rulebook queries.

Defines FastAPI endpoints that connect HTTP requests to controller logic
for uploading files and querying indexed documents.
"""

from controllers import chat_controller
from fastapi import APIRouter, File, Form, HTTPException, UploadFile
from logger import logger
from models.api_models import (
    ClearRAGResponse,
    QueryRequest,
    QueryResponse,
    UploadResponse,
)

router = APIRouter(prefix="/chat", tags=["RAG"])


@router.post("/upload/", response_model=UploadResponse)
async def upload_document(
    file: UploadFile = File(...), rag_type: str = Form(..., regex="^(HRAG|TradRAG)$")
):
    """
    Upload a document to the server and (re)build the selected RAG index.

    Args:
        file (UploadFile): The document file to be uploaded.
        rag_type (str): The type of RAG index to build ("HRAG" or "TradRAG").

    Returns:
        UploadFileResponse: Upload metadata including filename and message.

    Raises:
        HTTPException: If an error occurs during file handling or saving.
    """
    logger.info(
        "Received upload request for file: %s with RAG type: %s",
        file.filename,
        rag_type,
    )
    try:
        response = await chat_controller.upload_document(file, rag_type)
        logger.info(
            "File %s uploaded and %s index built successfully.", file.filename, rag_type
        )
        return response
    except HTTPException as e:
        logger.error("HTTPException during file upload: %s", e.detail, exc_info=True)
        raise e
    except Exception as e:
        logger.error(
            "An unexpected error occurred during file upload: %s", e, exc_info=True
        )
        raise HTTPException(
            status_code=500, detail=f"Internal server error: {e}"
        ) from e


@router.post("/queryHRAG", response_model=QueryResponse)
async def query_hrag(request: QueryRequest):
    """
    Query document using the Hierarchical RAG (HRAG) system with a user-provided question.

    Forwards the query to the controller which interacts with
    the LLM-powered query engine.

    Args:
        request (QueryRequest): Contains the user's query text.

    Returns:
        QueryResponse: The answer generated by the query engine.

    Raises:
        HTTPException: If the query engine fails or is not initialized.
    """
    logger.info("Received query request: %s", request.query)
    try:
        response = await chat_controller.query_hrag(request.query)
        logger.info("Query successfully processed.")
        return response
    except HTTPException as e:
        logger.error("HTTPException during rulebook query: %s", e.detail, exc_info=True)
        raise e
    except Exception as e:
        logger.error(
            "An unexpected error occurred during rulebook query: %s", e, exc_info=True
        )
        raise HTTPException(
            status_code=500, detail=f"Internal server error: {e}"
        ) from e


@router.post("/queryTradRAG", response_model=QueryResponse)
async def query_trad_rag(request: QueryRequest):
    """
    Query the traditional RAG system with a user-provided question.

    Forwards the query to the controller which interacts with
    the LLM-powered query engine.

    Args:
        request (QueryRequest): Contains the user's query text.

    Returns:
        QueryResponse: The answer generated by the query engine.

    Raises:
        HTTPException: If the query engine fails or is not initialized.
    """
    logger.info("Received traditional RAG query request: '%s'", request.query)

    try:
        response = await chat_controller.query_trad_rag(request.query)
        logger.info("Traditional RAG query successfully processed.")
        return response
    except HTTPException as e:
        logger.error(
            "HTTPException during traditional RAG query: %s", e.detail, exc_info=True
        )
        raise e
    except Exception as e:
        logger.error(
            "An unexpected error occurred during traditional RAG query: %s",
            e,
            exc_info=True,
        )
        raise HTTPException(
            status_code=500, detail=f"Internal server error: {e}"
        ) from e


@router.post("/clearRAGDocs", response_model=ClearRAGResponse)
async def clear_rag_docs():
    """
    Clear the RAG index.

    """
    logger.info("Received RAG document clear request")

    try:
        response = await chat_controller.clear_docs()
        logger.info("RAG index cleared successfully.")
        return response
    except Exception as e:
        logger.error(
            "An unexpected error occurred during RAG document clearing: %s",
            e,
            exc_info=True,
        )
        raise HTTPException(
            status_code=500, detail=f"Internal server error: {e}"
        ) from e
