FROM python:3.12
# Setup an app user so the container doesn't run as the root user 
RUN useradd --create-home appuser
USER appuser
# Create dir for the app and set as working directory
WORKDIR /home/appuser/app
# Install the application dependencies
# --chown is used to give the user permissions to read files in the directory (mainly .env)
COPY --chown=appuser:appuser requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
# Copy in the source code
COPY --chown=appuser:appuser ./prototype ./src/prototype
# Add executables installed by pip to PATH
ENV PATH="/home/appuser/.local/bin:$PATH"
# expose default ports
EXPOSE 8000

WORKDIR /home/appuser/app/src/prototype

CMD python -m backend_server.app